country_list = [
    ('AFG', 'Afghanistan'),
    ('ALB', 'Albania'),
    ('ALG', 'Algeria'),
    ('AND', 'Andorra'),
    ('ANG', 'Angola'),
    ('ANT', 'Antigua and Barbuda'),
    ('ARG', 'Argentina'),
    ('ARM', 'Armenia'),
    ('ARU', 'Aruba'),
    ('AUS', 'Australia'),
    ('AUT', 'Austria'),
    ('AZE', 'Azerbaijan'),
    ('BAH', 'Bahamas'),
    ('BRN', 'Bahrain'),
    ('BAN', 'Bangladesh'),
    ('BAR', 'Barbados'),
    ('BLR', 'Belarus'),
    ('BEL', 'Belgium'),
    ('BIZ', 'Belize'),
    ('BEN', 'Benin'),
    ('BER', 'Bermuda'),
    ('BHU', 'Bhutan'),
    ('BOL', 'Bolivia'),
    ('BIH', 'Bosnia and Herzegovina'),
    ('BOT', 'Botswana'),
    ('BRA', 'Brazil'),
    ('BRU', 'Brunei'),
    ('BUL', 'Bulgaria'),
    ('BUR', 'Burkina Faso'),
    ('BDI', 'Burundi'),
    ('CAM', 'Cambodia'),
    ('CMR', 'Cameroon'),
    ('CAN', 'Canada'),
    ('CPV', 'Cape Verde'),
    ('CAY', 'Cayman Islands'),
    ('CAF', 'Central African Republic'),
    ('CHA', 'Chad'),
    ('CHI', 'Chile'),
    ('CHN', 'China'),
    ('COL', 'Colombia'),
    ('COM', 'Comoros'),
    ('CGO', 'Congo'),
    ('COD', 'Congo (Democratic Republic)'),
    ('COK', 'Cook Islands'),
    ('CRC', 'Costa Rica'),
    ('CIV', 'Côte d\'Ivoire'),
    ('CRO', 'Croatia'),
    ('CUB', 'Cuba'),
    ('CYP', 'Cyprus'),
    ('CZE', 'Czech Republic'),
    ('DEN', 'Denmark'),
    ('DJI', 'Djibouti'),
    ('DMA', 'Dominica'),
    ('DOM', 'Dominican Republic'),
    ('ECU', 'Ecuador'),
    ('EGY', 'Egypt'),
    ('ESA', 'El Salvador'),
    ('GEQ', 'Equatorial Guinea'),
    ('ERI', 'Eritrea'),
    ('EST', 'Estonia'),
    ('SWZ', 'Eswatini'),
    ('ETH', 'Ethiopia'),
    ('FIJ', 'Fiji'),
    ('FIN', 'Finland'),
    ('FRA', 'France'),
    ('GAB', 'Gabon'),
    ('GAM', 'Gambia'),
    ('GEO', 'Georgia'),
    ('GER', 'Germany'),
    ('GHA', 'Ghana'),
    ('GBR', 'Great Britain'),
    ('GRE', 'Greece'),
    ('GRN', 'Grenada'),
    ('GUM', 'Guam'),
    ('GUA', 'Guatemala'),
    ('GUI', 'Guinea'),
    ('GBS', 'Guinea-Bissau'),
    ('GUY', 'Guyana'),
    ('HAI', 'Haiti'),
    ('HON', 'Honduras'),
    ('HKG', 'Hong Kong'),
    ('HUN', 'Hungary'),
    ('ISL', 'Iceland'),
    ('IND', 'India'),
    ('INA', 'Indonesia'),
    ('IRI', 'Iran'),
    ('IRQ', 'Iraq'),
    ('IRL', 'Ireland'),
    ('ISR', 'Israel'),
    ('ITA', 'Italy'),
    ('JAM', 'Jamaica'),
    ('JPN', 'Japan'),
    ('JOR', 'Jordan'),
    ('KAZ', 'Kazakhstan'),
    ('KEN', 'Kenya'),
    ('KIR', 'Kiribati'),
    ('PRK', 'Korea (North)'),
    ('KOR', 'Korea (South)'),
    ('KOS', 'Kosovo'),
    ('KUW', 'Kuwait'),
    ('KGZ', 'Kyrgyzstan'),
    ('LAO', 'Laos'),
    ('LAT', 'Latvia'),
    ('LIB', 'Lebanon'),
    ('LES', 'Lesotho'),
    ('LBR', 'Liberia'),
    ('LBA', 'Libya'),
    ('LIE', 'Liechtenstein'),
    ('LTU', 'Lithuania'),
    ('LUX', 'Luxembourg'),
    ('MAC', 'Macao'),
    ('MAD', 'Madagascar'),
    ('MAW', 'Malawi'),
    ('MAL', 'Malaysia'),
    ('MDV', 'Maldives'),
    ('MLI', 'Mali'),
    ('MLT', 'Malta'),
    ('MHL', 'Marshall Islands'),
    ('MTN', 'Mauritania'),
    ('MRI', 'Mauritius'),
    ('MEX', 'Mexico'),
    ('FSM', 'Micronesia'),
    ('MDA', 'Moldova'),
    ('MON', 'Monaco'),
    ('MGL', 'Mongolia'),
    ('MNE', 'Montenegro'),
    ('MAR', 'Morocco'),
    ('MOZ', 'Mozambique'),
    ('MYA', 'Myanmar'),
    ('NAM', 'Namibia'),
    ('NRU', 'Nauru'),
    ('NEP', 'Nepal'),
    ('NED', 'Netherlands'),
    ('NZL', 'New Zealand'),
    ('NCA', 'Nicaragua'),
    ('NIG', 'Niger'),
    ('NGR', 'Nigeria'),
    ('MKD', 'North Macedonia'),
    ('NOR', 'Norway'),
    ('OMA', 'Oman'),
    ('PAK', 'Pakistan'),
    ('PLW', 'Palau'),
    ('PLE', 'Palestine'),
    ('PAN', 'Panama'),
    ('PNG', 'Papua New Guinea'),
    ('PAR', 'Paraguay'),
    ('PER', 'Peru'),
    ('PHI', 'Philippines'),
    ('POL', 'Poland'),
    ('POR', 'Portugal'),
    ('PUR', 'Puerto Rico'),
    ('QAT', 'Qatar'),
    ('ROU', 'Romania'),
    ('RUS', 'Russia'),
    ('RWA', 'Rwanda'),
    ('SKN', 'Saint Kitts and Nevis'),
    ('LCA', 'Saint Lucia'),
    ('VIN', 'Saint Vincent and the Grenadines'),
    ('SAM', 'Samoa'),
    ('SMR', 'San Marino'),
    ('STP', 'São Tomé and Príncipe'),
    ('KSA', 'Saudi Arabia'),
    ('SEN', 'Senegal'),
    ('SRB', 'Serbia'),
    ('SEY', 'Seychelles'),
    ('SLE', 'Sierra Leone'),
    ('SGP', 'Singapore'),
    ('SVK', 'Slovakia'),
    ('SLO', 'Slovenia'),
    ('SOL', 'Solomon Islands'),
    ('SOM', 'Somalia'),
    ('RSA', 'South Africa'),
    ('SSD', 'South Sudan'),
    ('ESP', 'Spain'),
    ('SRI', 'Sri Lanka'),
    ('SUD', 'Sudan'),
    ('SUR', 'Suriname'),
    ('SWE', 'Sweden'),
    ('SUI', 'Switzerland'),
    ('SYR', 'Syria'),
    ('TPE', 'Taiwan'),
    ('TJK', 'Tajikistan'),
    ('TAN', 'Tanzania'),
    ('THA', 'Thailand'),
    ('TLS', 'Timor-Leste'),
    ('TOG', 'Togo'),
    ('TON', 'Tonga'),
    ('TTO', 'Trinidad and Tobago'),
    ('TUN', 'Tunisia'),
    ('TUR', 'Turkey'),
    ('TKM', 'Turkmenistan'),
    ('TUV', 'Tuvalu'),
    ('UGA', 'Uganda'),
    ('UKR', 'Ukraine'),
    ('UAE', 'United Arab Emirates'),
    ('URU', 'Uruguay'),
    ('USA', 'United States'),
    ('UZB', 'Uzbekistan'),
    ('VAN', 'Vanuatu'),
    ('VAT', 'Vatican City'),
    ('VEN', 'Venezuela'),
    ('VIE', 'Vietnam'),
    ('ISV', 'Virgin Islands (US)'),
    ('YEM', 'Yemen'),
    ('ZAM', 'Zambia'),
    ('ZIM', 'Zimbabwe')
]